
 
version: "3.0"

services:
  flask-api:
    build: .
    container_name: flask-api
    image: ex-flask-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - my-net

  ex-prometheus:
    image: prom/prometheus:latest
    container_name: ex-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
   
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - my-net
   
  ex-grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: ex-grafana
    depends_on:
      - ex-prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./monitoring/config.monitoring
    networks:
      - my-net

networks:
  my-net: 
    driver: bridge

